### ISSUE TITLE
Testing on a EK-TM4C123GXL

### ISSUE THREAD

**Issue by tomy983** [altineller/fximu_firmware#1]
Hello,
I wanted to try the code on the launchpad evaluation board. I successfully compiled it and loaded into the board following your instructions (with some changes).
I do not have any sensor attached (I only have the launchpad board without anything else), because before buying the sensors (I was thinking on getting the https://www.adafruit.com/product/3463) I wanted to make sure that I could make to this step.
I have an issue though.. Once the firmware is loaded onto the launchpad, I move the USB cable from the debug port to the device port and flip the power switch. The board turns on and the blue led light up, but I was expecting to be able to find the board among the PC USB devices, as a COM port, but instead nothing comes up (I also tried the debug port, I can open it but no communications on that). Is this normal? is the program looking for the sensors before opening the serial port? Is what I am attempting even doable?
Thank you

**Comment by altineller** [comment]
Hello,

Yes what you are doing is achievable. Indeed, fximu was developed with the tiva-c launchpad, and adafruit product 3463.

The board will not initialize if sensors are not detected.

The launchpad has 2 usb ports, 1 is called the normal debug port, and the one on the side is usb-cdc, which is connected the the mcu directly. After you program the launchpad via debug port, you can flip the switch and connect to usb-cdc, and provided that the sensors initialized, it will start talking to ROS.

you can maybe comment out the sensor checking part, but what happens if no sensor is in place, the mcu sends i2c packets and unable to send, it crashes completely. 

Best Regards,
Can

**Comment by tomy983** [comment]
Thank you, will let you know how it goes.

**Comment by tomy983** [comment]
Hi @altineller, I just wanted to let you know that I managed to get it working on the launchpad.. Thank you for your work! I still have some troubles with it in a particular place where magnetic interferences are high, but otherwise working well!

**Comment by altineller** [comment]
@tomy983 greetings, and congratulations. I have finally produced few of them, manually by hand, and listed them on tindie, FYI.
Best Regards, Can
